"""Hand-written glosses for the Phase 4 readout tokens, produced without the API.

**This file is not pipeline output, and it is not an audited artefact like**
:mod:`analysis.zh_en_glossary`. It exists for one reason: ``ANTHROPIC_API_KEY`` is not
available in this checkout, and STEP 2 of :mod:`analysis.translate_readouts` needs a
gloss source. These glosses were written by an assistant (Claude) reading the token
list directly, rather than by the batched API path that script normally uses.

Provenance and standing
-----------------------
Each entry lands in ``analysis/translation_cache.json`` tagged
``"source": "assistant-offline"``, so any consumer can tell these apart from
``"zh_en_glossary"`` (human, pre-committed) and from ``"api-<model>"`` entries. Replace
any of them by adding a key to the cache with a different source; the cache always wins
over this table.

**These glosses carry no inferential weight.** They are a reading aid for the token
tables, in the same standing the :mod:`analysis.zh_en_glossary` docstring gives its own
PC-end glosses. In particular they were written *after* seeing the readouts, so they are
contaminated for any purpose that scores the readouts against a gloss list -- do **not**
feed them into a cross-lingual GATE A. :mod:`analysis.zh_en_glossary` is the
pre-committed table for that; it stays untouched.

Confidence follows the same rule the API prompt uses: ``high`` = confident of both sense
and usage, ``medium`` = clear meaning but the fragment is ambiguous or register-specific,
``low`` = a guess. Fragments are glossed *as fragments* and never completed into a
plausible whole word.
"""

from __future__ import annotations

#: ``exact token`` -> ``(english gloss, confidence)``. Keys are matched after stripping,
#: so a leading-space variant of the same token resolves here too.
OFFLINE_GLOSS: dict[str, tuple[str, str]] = {
    # ---- Chinese: emotion and affect ------------------------------------------------
    "无聊": ("bored; boring, tedious", "high"),
    "惬意": ("pleasantly comfortable, contented", "high"),
    "恐惧": ("fear, dread", "high"),
    "恐怖": ("terror, horror", "high"),
    "开心": ("happy, delighted", "high"),
    "感动": ("moved, touched emotionally", "high"),
    "欣慰": ("gratified; relieved and pleased", "high"),
    "焦虑": ("anxiety; anxious", "high"),
    "兴奋": ("excited, worked up", "high"),
    "愉悦": ("pleasure; delighted", "high"),
    "幸福": ("happiness; blessed, fortunate", "high"),
    "幸福感": ("sense of wellbeing, felt happiness", "high"),
    "欢乐": ("joy, merriment", "high"),
    "寂寞": ("lonely, lonesome", "high"),
    "尴尬": ("awkward, embarrassed", "high"),
    "厌恶": ("to loathe; disgust", "high"),
    "嫌弃": ("to find distasteful, shun", "high"),
    "恶心": ("disgusting, nauseating", "high"),
    "嫉妒": ("jealousy, envy", "high"),
    "后悔": ("to regret", "high"),
    "怀念": ("to miss, reminisce about", "high"),
    "无助": ("helpless", "high"),
    "沉重": ("heavy, weighed down (of grief)", "high"),
    "挣扎": ("to struggle", "high"),
    "抱怨": ("to complain", "high"),
    "讨厌": ("to dislike; annoying", "high"),
    "吐槽": ("to snark at, gripe about (internet slang)", "high"),
    "倒霉": ("unlucky, out of luck", "high"),
    "糟糕": ("terrible, awful", "high"),
    "激情": ("passion, fervour", "high"),
    "热烈": ("ardent, enthusiastic", "high"),
    "热血": ("hot-blooded, impassioned", "high"),
    "振奋": ("to rouse, invigorate", "high"),
    "鼓舞": ("to inspire, hearten", "high"),
    "自豪": ("proud (of)", "high"),
    "骄傲": ("proud; pride, arrogance", "high"),
    "安慰": ("to comfort, console", "high"),
    "温情": ("warmth, tenderness", "high"),
    "亲情": ("family affection", "high"),
    "友好": ("friendly", "high"),
    "善良": ("kind-hearted", "high"),
    "幽默": ("humour", "high"),
    "搞笑": ("funny, comedic", "high"),
    "放松": ("to relax", "high"),
    "轻松": ("relaxed, effortless", "high"),
    "休闲": ("leisure; casual", "high"),
    "悠闲": ("leisurely, carefree", "high"),
    "静静": ("quietly, silently", "high"),
    "耐心": ("patience", "high"),
    "泪水": ("tears", "high"),
    "悲剧": ("tragedy", "high"),
    "苦难": ("suffering, hardship", "high"),
    "挫折": ("setback, frustration", "high"),
    "困境": ("predicament, difficult straits", "high"),
    "疯": ("mad, crazy; single char of 疯狂 'frenzied'", "medium"),
    "瘋": ("traditional form of 疯: mad, crazy", "medium"),
    "悠": ("leisurely / long-drawn; bound char of 悠闲, 悠久", "medium"),
    "恋": ("romantic love; bound char of 恋爱", "medium"),
    "悍": ("fierce, tough; bound char of 强悍", "medium"),
    "劣": ("inferior, of poor quality; bound morpheme", "medium"),
    "熠": ("glittering; bound char of 熠熠 'sparkling'", "low"),
    "杳": ("vanished without trace; bound, as in 杳无音信", "low"),
    "痊": ("to recover from illness; bound char of 痊愈", "medium"),
    "痉": ("spasm; bound char of 痉挛 'convulsion'", "low"),
    "锃": ("gleaming, polished; bound char of 锃亮", "low"),
    "噱": ("bound char of 噱头 'gimmick, sales hook'", "low"),
    "诬": ("to falsely accuse; bound, as in 诬告, 诬陷", "medium"),
    "漂": ("to float, or to bleach; also first char of 漂亮 'pretty'", "low"),
    "斧": ("axe", "high"),
    "谜": ("riddle, mystery", "high"),
    "砰": ("bang, thud (onomatopoeia)", "high"),
    # ---- Chinese: violence, crime, policing -----------------------------------------
    "屠杀": ("massacre, slaughter", "high"),
    "杀人": ("to kill a person; homicide", "high"),
    "杀死": ("to kill (something) dead", "high"),
    "摧毁": ("to destroy, demolish", "high"),
    "毁灭": ("annihilation, ruin", "high"),
    "残酷": ("cruel, brutal", "high"),
    "残忍": ("cruel, merciless", "high"),
    "报复": ("revenge, retaliation", "high"),
    "复仇": ("vengeance", "high"),
    "受害者": ("victim", "high"),
    "受伤": ("to be injured", "high"),
    "伤害": ("to harm; injury", "high"),
    "牺牲": ("to sacrifice; a casualty", "high"),
    "死去": ("to die, pass away", "high"),
    "致命": ("fatal, lethal", "high"),
    "灾难": ("disaster, catastrophe", "high"),
    "危机": ("crisis", "high"),
    "紧急": ("urgent, emergency", "high"),
    "警察": ("police officer", "high"),
    "警方": ("the police (as an institution)", "high"),
    "派出所": ("local police station", "high"),
    "保安": ("security guard", "high"),
    "安保": ("security (provision, services)", "high"),
    "安防": ("security and protection (as an industry)", "high"),
    "国家安全": ("national security", "high"),
    "嫌疑人": ("suspect (criminal)", "high"),
    "可疑": ("suspicious, dubious", "high"),
    "隐蔽": ("concealed, covert", "high"),
    "侦查": ("to investigate (a crime)", "high"),
    "偵": ("traditional form of 侦: to detect, investigate", "medium"),
    "防止": ("to prevent, guard against", "high"),
    "流氓": ("hooligan, rogue; obscene, indecent", "high"),
    "腐败": ("corruption; rotten", "high"),
    "抄袭": ("plagiarism, to plagiarise", "high"),
    "歧视": ("discrimination", "high"),
    "抗议": ("to protest", "high"),
    "谴责": ("to condemn, denounce", "high"),
    "批评": ("to criticise", "high"),
    "嘲笑": ("to mock, ridicule", "high"),
    "质疑": ("to question, call into doubt", "high"),
    "问责": ("to hold to account", "high"),
    "惩罚": ("to punish; punishment", "high"),
    "处罚": ("penalty; to penalise", "high"),
    "罚款": ("fine, monetary penalty", "high"),
    "整改措施": ("rectification measures (官方 official register)", "high"),
    "揭露": ("to expose, bring to light", "high"),
    "忽悠": ("to hoodwink, sweet-talk (colloquial)", "high"),
    "负面": ("negative (side, coverage)", "high"),
    "有毒": ("toxic, poisonous", "high"),
    # ---- Chinese: intensity, change, scale ------------------------------------------
    "蹿": ("to shoot up, leap (of prices, flames)", "medium"),
    "暴跌": ("to plummet (prices, markets)", "high"),
    "急剧": ("sharply, drastically", "high"),
    "猛然": ("abruptly, all at once", "high"),
    "猛地": ("abruptly, with a jerk", "high"),
    "突然": ("suddenly", "high"),
    "突如其": ("fragment of 突如其来 'out of nowhere, sudden'", "high"),
    "莫名其": ("fragment of 莫名其妙 'inexplicable, baffling'", "high"),
    "爆发": ("to erupt, break out", "high"),
    "冲刺": ("sprint, final push", "high"),
    "超强": ("super-strong, ultra-powerful", "high"),
    "强悍": ("fierce, formidable", "high"),
    "惊人": ("astonishing, staggering", "high"),
    "震撼": ("to shake, stun; stunning", "high"),
    "无比": ("incomparably (intensifying suffix)", "high"),
    "统统": ("entirely, the whole lot", "high"),
    "火热": ("fiery, red-hot", "high"),
    "被迫": ("to be forced to", "high"),
    "无法": ("unable to, no way to", "high"),
    "未能": ("failed to, was unable to", "high"),
    "失效": ("to become invalid, cease to work", "high"),
    "丢失": ("to lose, go missing", "high"),
    "丧失": ("to lose (a faculty, a right)", "high"),
    "失去了": ("lost (失去 + perfective 了)", "high"),
    "受损": ("to be damaged, impaired", "high"),
    "浪费": ("to waste", "high"),
    "消失": ("to vanish, disappear", "high"),
    "停滞": ("stagnation, to stagnate", "high"),
    "等待": ("to wait", "high"),
    "复苏": ("to revive, recover (economy, spirits)", "high"),
    "重启": ("to restart, reboot", "high"),
    "康复": ("to recuperate, convalesce", "high"),
    "治愈": ("to heal; healing, comforting", "high"),
    "治疗": ("treatment; to treat medically", "high"),
    "睡眠": ("sleep", "high"),
    "休息": ("to rest", "high"),
    "退休": ("to retire", "high"),
    # ---- Chinese: praise, beauty, spectacle -----------------------------------------
    "神奇": ("magical, marvellous", "high"),
    "奇迹": ("miracle", "high"),
    "不可思议": ("inconceivable, incredible", "high"),
    "神秘": ("mysterious", "high"),
    "神话": ("myth, legend", "high"),
    "辉煌": ("brilliant, glorious", "high"),
    "光辉": ("radiance, glory", "high"),
    "光芒": ("rays of light, radiance", "high"),
    "耀眼": ("dazzling", "high"),
    "熠熠": ("glittering", "high"),
    "惊艳": ("stunningly beautiful", "high"),
    "靓丽": ("pretty, gorgeous", "high"),
    "魅力": ("charm, allure", "high"),
    "颜值": ("'face value', physical attractiveness (slang)", "high"),
    "典雅": ("elegant, refined", "high"),
    "奢华": ("luxurious, opulent", "high"),
    "精湛": ("consummate, exquisite (of skill)", "high"),
    "优良": ("fine, superior", "high"),
    "绝佳": ("excellent, first-rate", "high"),
    "美好": ("fine, lovely (of times, things)", "high"),
    "难忘": ("unforgettable", "high"),
    "珍贵": ("precious", "high"),
    "清新": ("fresh, refreshing", "high"),
    "柔软": ("soft, supple", "high"),
    "细腻": ("delicate, fine-grained", "high"),
    "稳固": ("stable, firm", "high"),
    "稳妥": ("safe and reliable, prudent", "high"),
    "坚韧": ("tough, resilient", "high"),
    "才华": ("talent, flair", "high"),
    "灵感": ("inspiration", "high"),
    "展示": ("to display, showcase", "high"),
    "炫耀": ("to show off, flaunt", "high"),
    "霸气": ("domineering, commanding presence", "high"),
    "夺冠": ("to win the championship", "high"),
    "赢家": ("winner", "high"),
    "征服": ("to conquer", "high"),
    "有望": ("promising, likely to", "high"),
    "探索": ("to explore", "high"),
    "爆款": ("runaway bestseller (e-commerce slang)", "high"),
    "网红": ("internet celebrity, influencer", "high"),
    "豪车": ("luxury car", "high"),
    "美食": ("fine food, delicacies", "high"),
    "饮品": ("drinks, beverages", "high"),
    "田园": ("rural, pastoral", "high"),
    "散步": ("to take a walk", "high"),
    "喝酒": ("to drink alcohol", "high"),
    "旅程": ("journey", "high"),
    "岁月": ("the years, passing time", "high"),
    "时光": ("time, days (nostalgic register)", "high"),
    "往事": ("past events, bygones", "high"),
    "记忆": ("memory", "high"),
    "铭记": ("to engrave in memory, never forget", "high"),
    "纪念": ("to commemorate; a memento", "high"),
    "近年": ("in recent years", "high"),
    "祝福": ("blessing; to wish well", "high"),
    "爱情": ("romantic love", "high"),
    "恋爱": ("to be in love; a romance", "high"),
    "初恋": ("first love", "high"),
    "尊重": ("respect", "high"),
    # ---- Chinese: news, documentary, everyday register ------------------------------
    "照片": ("photograph", "high"),
    "摄影师": ("photographer", "high"),
    "摄影作品": ("photographic work", "high"),
    "考古": ("archaeology", "high"),
    "化石": ("fossil", "high"),
    "宇宙": ("universe, cosmos", "high"),
    "科学": ("science", "high"),
    "研究人员": ("researchers", "high"),
    "资料显示": ("'the data show' (news phrase)", "high"),
    "陈述": ("to state; a statement", "high"),
    "声称": ("to claim, allege", "high"),
    "传闻": ("rumour, hearsay", "high"),
    "疑似": ("suspected to be, apparently", "high"),
    "不明": ("unclear, unidentified", "high"),
    "疑问": ("doubt, open question", "high"),
    "询问": ("to inquire, question", "high"),
    "讨论": ("to discuss", "high"),
    "探访": ("to visit, call on", "high"),
    "目睹": ("to witness first-hand", "high"),
    "担忧": ("to worry; concern", "high"),
    "官员": ("government official", "high"),
    "顾问": ("advisor, consultant", "high"),
    "諮詢": ("traditional form of 咨询: consultation, advisory", "high"),
    "老板": ("boss, proprietor", "high"),
    "患者": ("patient (medical)", "high"),
    "病人": ("sick person, patient", "high"),
    "老人": ("elderly person", "high"),
    "老头": ("old man (colloquial, familiar)", "high"),
    "家人": ("family members", "high"),
    "闺蜜": ("close female friend", "high"),
    "这家伙": ("'this guy', this fellow", "high"),
    "你们": ("you (plural)", "high"),
    "他们": ("they, them", "high"),
    "咱们": ("we, us (inclusive of the listener)", "high"),
    "人物": ("figure, personage; character", "high"),
    "物体": ("physical object", "high"),
    "词语": ("word, term", "high"),
    "文化交流": ("cultural exchange", "high"),
    "桌子": ("table", "high"),
    "客房": ("guest room", "high"),
    "楼层": ("storey, floor of a building", "high"),
    "垃圾桶": ("rubbish bin", "high"),
    "院子里": ("in the courtyard", "high"),
    "那边": ("over there", "high"),
    "便宜": ("cheap, inexpensive", "high"),
    "廉价": ("cheap, low-priced (often pejorative)", "high"),
    "高价": ("high price", "high"),
    "昂贵": ("expensive, costly", "high"),
    "没钱": ("to have no money", "high"),
    "赚钱": ("to make money", "high"),
    "负担": ("burden", "high"),
    "缺席": ("absent, absence", "high"),
    "懒": ("lazy", "high"),
    "注意到": ("to notice", "high"),
    "帮你": ("'help you' (帮 + 你)", "high"),
    "分钟左右": ("'about N minutes'", "high"),
    "至於": ("traditional form of 至于: as for, as to", "high"),
    # ---- Chinese: grammatical / phrasal fragments -----------------------------------
    "不太": ("'not very' (adverbial fragment)", "high"),
    "有点": ("'a bit, somewhat'", "high"),
    "太多": ("'too many, too much'", "high"),
    "有一些": ("'there are some'", "high"),
    "没什么": ("'nothing much, never mind'", "high"),
    "也没什么": ("'and it's nothing much either'", "high"),
    "根本没有": ("'there is none at all'", "high"),
    "说不定": ("'maybe, who knows'", "high"),
    "不会再": ("'will not ... again'", "high"),
    "有必要": ("'it is necessary'", "high"),
    "问题是": ("'the problem is'", "high"),
    "其它问题": ("'other problems'", "high"),
    "比较简单": ("'relatively simple'", "high"),
    "做一些": ("'to do some'", "high"),
    "大家一起": ("'everyone together'", "high"),
    "的强大": ("'...'s power' (的 + 强大 'powerful')", "medium"),
    "的历史": ("'...'s history' (的 + 历史)", "medium"),
    "的目光": ("'...'s gaze' (的 + 目光)", "medium"),
    "伟大的": ("'great' + attributive 的", "high"),
    "美丽的": ("'beautiful' + attributive 的", "high"),
    "美好的": ("'fine, lovely' + attributive 的", "high"),
    "古老的": ("'ancient' + attributive 的", "high"),
    "优秀的": ("'excellent' + attributive 的", "high"),
    "精彩的": ("'brilliant, spectacular' + attributive 的", "high"),
    "深厚的": ("'deep, profound' + attributive 的", "high"),
    "閒": ("traditional form of 闲: idle, leisure", "high"),
    # ---- Japanese / Korean ----------------------------------------------------------
    "お互": ("fragment of お互い 'each other, mutually' (Japanese)", "medium"),
    "みんな": ("everyone, everybody (Japanese)", "high"),
    "すごい": ("amazing, incredible (Japanese)", "high"),
    "설명": ("explanation (Korean)", "high"),
    # ---- Cyrillic -------------------------------------------------------------------
    "практик": ("stem of практика / практический 'practice, practical'", "medium"),
    "индивид": ("individual (stem of индивидуальный)", "medium"),
    "индив": ("shorter fragment of индивид- 'individual'", "medium"),
    "российск": ("stem of российский 'Russian (of Russia)'", "medium"),
    "профессионал": ("professional (noun stem)", "high"),
    "благо": ("good, benefit; also stem of благодаря 'thanks to'", "medium"),
    "Почем": ("fragment of Почему 'why' (or почем 'how much')", "medium"),
    "зло": ("evil, harm", "high"),
    "ино": ("ино- prefix: other-, foreign- (иностранный)", "low"),
    "скоп": ("fragment: -скоп '-scope', or скопление 'accumulation'", "low"),
    "нарко": ("narco- prefix, as in наркотик 'narcotic'", "high"),
    "резидент": ("resident", "high"),
    "иногда": ("sometimes", "high"),
    "сообщил": ("reported, informed (masculine past)", "high"),
    "тради": ("fragment of традиция 'tradition'", "medium"),
    "безопасн": ("stem of безопасный / безопасность 'safe, security'", "medium"),
    "посколь": ("fragment of поскольку 'since, inasmuch as'", "medium"),
    "путеш": ("fragment of путешествие 'journey, travel'", "medium"),
    # ---- Thai / Arabic --------------------------------------------------------------
    "เทคโน": ("fragment of เทคโนโลยี 'technology'", "medium"),
    "โทษ": ("punishment, penalty; blame; harm", "high"),
    "นโย": ("fragment of นโยบาย 'policy'", "medium"),
    "مفاوضات": ("negotiations, talks", "high"),
    "مصلحة": ("interest, benefit; also a government bureau", "high"),
    "مصل": ("serum; also the stem of مصلحة 'interest'", "low"),
    # ---- Latin script, not English --------------------------------------------------
    "pornost": ("fragment of pornostar(s) / pornoster; porn-spam vocabulary", "medium"),
    "fetisch": ("fetish (German, Dutch)", "high"),
    "salopes": ("sluts (French, vulgar)", "high"),
    "erotik": ("erotica, erotic (German, Turkish, Scandinavian)", "high"),
    "Erotische": ("erotic (German, inflected adjective)", "high"),
    "erotisch": ("erotic (German, Dutch)", "high"),
    "erotisk": ("erotic (Danish, Swedish, Norwegian)", "high"),
    "prostituer": ("prostitute / to prostitute (French, Danish stem)", "medium"),
    "Prostitutas": ("prostitutes (Spanish, Portuguese)", "high"),
    "milfs": ("porn-spam slang plural; English but off-register", "high"),
    "lesbische": ("lesbian (German, Dutch, inflected adjective)", "high"),
    "strapon": ("strap-on (sex toy)", "high"),
    "Shemale": ("porn-industry term for a trans woman; slur", "high"),
    "eskort": ("escort (Scandinavian, Turkish)", "high"),
    "Geile": ("horny, randy (German, inflected)", "high"),
    "arsch": ("arse (German)", "high"),
    "pornô": ("porn (Portuguese)", "high"),
    "cumshot": ("porn-industry term", "high"),
    "Blowjob": ("porn-industry term", "high"),
    "amatør": ("amateur (Danish, Norwegian)", "high"),
    "coquine": ("naughty girl, minx (French)", "high"),
    "follando": ("fucking (Spanish, vulgar, gerund)", "high"),
    "neuken": ("to fuck (Dutch, vulgar)", "high"),
    "Bbw": ("BBW, porn-industry acronym", "high"),
    "damer": ("ladies (Danish, Norwegian, French)", "medium"),
    "modne": ("mature (Danish, Norwegian); or 'fashionable' (Polish)", "low"),
    "männer": ("men (German)", "high"),
    "köln": ("Cologne, the German city", "high"),
    "danmark": ("Denmark (Danish)", "high"),
    "ragaz": ("fragment of Italian ragazza / ragazzi 'girl, kids'", "medium"),
    "toplant": ("fragment of Turkish toplantı 'meeting'", "medium"),
    "Notíc": ("fragment of notícia 'news' (Portuguese, Spanish)", "medium"),
    "councill": ("fragment of council / councillor", "medium"),
    "ondrous": ("fragment of 'wondrous'", "high"),
    "gMaps": ("code identifier fragment, 'Google Maps'", "medium"),
    "iationException": ("tail of a Java/C# exception class name", "medium"),
    "wś": ("Polish fragment, likely wśród 'among' or wieś 'village'", "low"),
    "pobli": ("Polish fragment, likely w pobliżu 'nearby'", "low"),
    "dõ": ("fragment carrying a Portuguese/Vietnamese diacritic; unclear", "low"),
    # ---- Invisible control characters ------------------------------------------------
    "‎": ("LEFT-TO-RIGHT MARK: invisible bidi control, no lexical content", "high"),
    "​": ("ZERO WIDTH SPACE: invisible formatting, no lexical content", "high"),
}
