"""Hand-written Chinese<->English reference data for reading Phase 4.

**This file is not pipeline output.** Everything in it is a human translation
judgement, written by hand, and it is kept in its own module precisely so that it
can be audited separately from anything the pipeline measured. Nothing here changes
a Phase 4 artefact; the notebook joins against it to (a) make the token tables
legible and (b) run a relaxed, cross-lingual version of GATE A.

Why this exists
---------------
The Jacobian-lens readouts at block 31 are 43-61% CJK by token count, and GATE A
asks an English question ("does the emotion's own English word appear in the
vector's top-12?"). Two separate things could sink that test:

1. **Script.** The readout names the concept in Chinese, so an English lemma cannot
   appear no matter how good the direction is.
2. **Exact-lemma matching.** The readout offers ``sorrow`` when the test wants
   ``sad``; a near-synonym is not a hit.

GATE A conflates the two. :data:`EMOTION_ZH` and :data:`EMOTION_EN_SYNONYMS` let the
notebook separate them by scoring three nested tiers against the same top-12 lists.

Pre-commitment protocol
-----------------------
The honest failure mode here is fishing: writing translations *after* seeing which
tokens appeared, so that the synonym lists are quietly fitted to the answer. To
avoid it:

* :data:`EMOTION_ZH` and :data:`EMOTION_EN_SYNONYMS` were written from the 171
  emotion words alone, in one pass, and saved to this file **before** any matching
  code was run against ``phase4_readouts.csv``.
* Matching is **exact set membership** (after stripping whitespace and lowercasing
  Latin), not substring or fuzzy matching. A generous list is therefore visible as a
  generous list rather than hidden in a matcher.
* Both lists are printed in full in ``RESULTS.md`` so a reader can judge the
  generosity themselves and re-score with a stricter list if they disagree.

**Disclosed contamination.** Before writing these lists the author had already seen
the PC-end and a-priori-axis readouts (the ~51 CJK tokens in the notebook's Phase 4
token panels), and the five GATE A emotions the pipeline scored HIT. The author had
**not** seen the per-emotion top-12 token lists for the 171 emotions, which is what
the relaxed GATE A scores. The per-emotion result is therefore clean; the PC-end
glosses are a reading aid and carry no inferential weight.

Known limitation: multi-character Chinese phrases below are often not single tokens
in Qwen's vocabulary, so they can never match. That biases the Chinese tier
*downwards* -- it can under-count hits, not invent them.
"""

from __future__ import annotations

#: CJK tokens appearing in the notebook's Phase 4 token panels, plus every CJK token
#: occurring 5+ times across all readouts. Glosses are indicative, not canonical --
#: several of these are register-specific or are fragments of a longer word.
TOKEN_GLOSS: dict[str, str] = {
    "专项斗争": "special crackdown campaign (state slogan)",
    "亏损": "financial loss",
    "仇恨": "hatred",
    "优雅": "elegant, graceful",
    "伤心": "heartbroken, sad",
    "偶尔": "occasionally",
    "凶手": "murderer",
    "击杀": "kill, slay",
    "创意": "creative, creativity",
    "刽": "executioner (bound morpheme, 刽子手)",
    "可爱": "cute, lovable",
    "可爱的": "cute (attributive form)",
    "喜悦": "joy, delight",
    "嘭": "bang (onomatopoeia)",
    "失去": "lose, loss",
    "失控": "out of control",
    "失败": "failure, to fail",
    "失踪": "go missing",
    "嫌": "suspect, dislike (bound, 嫌疑)",
    "害怕": "afraid, to fear",
    "尖叫": "scream",
    "崩溃": "collapse, breakdown",
    "帅哥": "handsome guy",
    "庆典": "celebration, ceremony",
    "引爆": "detonate, set off",
    "得罪": "offend, give offence",
    "恐慌": "panic",
    "悲伤": "sadness, sorrow",
    "惙": "anxious, exhausted (rare classical char)",
    "愉快": "pleasant, cheerful",
    "感人": "moving, touching",
    "愤怒": "anger, furious",
    "扫黑除恶": "crack down on gangs and evil (state campaign slogan)",
    "抑郁症": "depression (clinical)",
    "拒绝": "refuse, reject",
    "拼命": "desperately, with all one's might",
    "指责": "blame, accuse",
    "旅途": "journey",
    "无力": "powerless, weak",
    "无数": "countless",
    "暖心": "heartwarming",
    "暴力": "violence",
    "暴涨": "surge, soar sharply",
    "有毒": "toxic, poisonous",
    "柔和": "soft, gentle",
    "欢呼": "cheer, acclaim",
    "欢快": "cheerful, lively",
    "欣喜": "delighted, glad",
    "死亡": "death",
    "活力": "vitality, energy",
    "活泼": "lively, vivacious",
    "温和": "mild, gentle",
    "温暖": "warm",
    "温柔": "tender, gentle",
    "温馨": "cosy, warm (of atmosphere)",
    "火爆": "explosive, hot-tempered, booming",
    "炫": "dazzle, flashy",
    "爆炸": "explosion",
    "爱心": "loving heart, compassion",
    "狂欢": "revelry, carnival",
    "狠狠": "fiercely, ruthlessly",
    "狰": "ferocious (bound morpheme, 狰狞)",
    "璀璨": "resplendent, brilliant",
    "甜美": "sweet, lovely",
    "甜蜜": "sweet (affectionate)",
    "生病": "fall ill",
    "疯狂": "crazy, frenzied",
    "痛苦": "pain, suffering",
    "科学家": "scientist",
    "绚丽": "gorgeous, splendid",
    "绝望": "despair, hopeless",
    "缺乏": "lack, deficiency",
    "罪": "crime, guilt, sin",
    "罵": "scold, curse (traditional form of 骂)",
    "美味": "delicious",
    "美妙": "wonderful, marvellous",
    "血腥": "bloody, gory",
    "警告": "warning",
    "讽刺": "irony, sarcasm",
    "迅猛": "swift and fierce",
    "震惊": "shocked, stunned",
    "飙升": "soar, skyrocket",
    "骂": "scold, curse",
    "黑名单": "blacklist",
    "黑恶势力": "criminal gangs and evil forces (state campaign term)",
}

#: emotion -> plausible Chinese renderings. Matched by exact token equality.
EMOTION_ZH: dict[str, list[str]] = {
    "afraid": ["害怕", "恐惧", "畏惧", "惧怕"],
    "alarmed": ["警觉", "惊慌", "警报", "震惊"],
    "alert": ["警觉", "警惕", "警报", "提醒"],
    "amazed": ["惊讶", "惊奇", "震惊", "惊叹"],
    "amused": ["有趣", "好笑", "逗乐", "娱乐"],
    "angry": ["愤怒", "生气", "恼怒", "发怒", "怒"],
    "annoyed": ["恼火", "烦躁", "厌烦", "恼怒"],
    "anxious": ["焦虑", "担心", "不安", "忧虑"],
    "aroused": ["兴奋", "激动", "唤醒", "激发"],
    "ashamed": ["羞愧", "惭愧", "羞耻", "耻辱"],
    "astonished": ["惊讶", "震惊", "惊愕", "吃惊"],
    "at ease": ["放松", "自在", "舒适", "安心"],
    "awestruck": ["敬畏", "震撼", "惊叹"],
    "bewildered": ["困惑", "迷惑", "茫然", "不解"],
    "bitter": ["苦涩", "怨恨", "痛苦", "苦"],
    "blissful": ["幸福", "极乐", "喜悦", "美满"],
    "bored": ["无聊", "厌倦", "枯燥", "乏味"],
    "brooding": ["沉思", "忧郁", "郁闷"],
    "calm": ["平静", "冷静", "镇静", "安静", "温和"],
    "cheerful": ["快乐", "开朗", "愉快", "欢快"],
    "compassionate": ["同情", "慈悲", "怜悯", "爱心"],
    "contemptuous": ["蔑视", "轻蔑", "鄙视"],
    "content": ["满足", "知足", "满意"],
    "defiant": ["反抗", "挑衅", "违抗", "倔强"],
    "delighted": ["高兴", "喜悦", "欣喜", "愉快"],
    "dependent": ["依赖", "依靠", "依存"],
    "depressed": ["抑郁", "沮丧", "消沉", "抑郁症"],
    "desperate": ["绝望", "拼命", "不顾一切"],
    "disdainful": ["轻蔑", "鄙视", "不屑"],
    "disgusted": ["厌恶", "恶心", "反感", "憎恶"],
    "disoriented": ["迷失", "茫然", "迷惑", "混乱"],
    "dispirited": ["沮丧", "灰心", "气馁"],
    "distressed": ["痛苦", "苦恼", "忧虑", "悲痛"],
    "disturbed": ["不安", "困扰", "扰乱", "心烦"],
    "docile": ["温顺", "顺从", "听话"],
    "droopy": ["无精打采", "下垂", "萎靡"],
    "dumbstruck": ["目瞪口呆", "哑口无言", "震惊"],
    "eager": ["渴望", "热切", "急切", "迫切"],
    "ecstatic": ["狂喜", "欣喜若狂", "兴奋", "狂欢"],
    "elated": ["兴高采烈", "欣喜", "得意", "高兴"],
    "embarrassed": ["尴尬", "难堪", "羞愧", "窘迫"],
    "empathetic": ["共情", "同理心", "同情"],
    "energized": ["充满活力", "精力充沛", "活力"],
    "enraged": ["暴怒", "愤怒", "激怒", "狂怒"],
    "enthusiastic": ["热情", "热忱", "积极", "热衷"],
    "envious": ["嫉妒", "羡慕", "妒忌"],
    "euphoric": ["欣快", "狂喜", "陶醉"],
    "exasperated": ["恼怒", "气愤", "恼火"],
    "excited": ["兴奋", "激动", "期待"],
    "exuberant": ["充满活力", "热情洋溢", "兴高采烈", "活力"],
    "frightened": ["害怕", "惊恐", "恐惧", "吓"],
    "frustrated": ["沮丧", "挫败", "受挫", "失望"],
    "fulfilled": ["满足", "充实", "实现"],
    "furious": ["愤怒", "暴怒", "狂怒", "火爆"],
    "gloomy": ["忧郁", "阴郁", "沮丧", "阴沉"],
    "grateful": ["感激", "感谢", "感恩"],
    "greedy": ["贪婪", "贪心", "贪"],
    "grief-stricken": ["悲痛", "悲伤", "哀伤", "沉痛"],
    "grumpy": ["暴躁", "易怒", "不高兴", "脾气坏"],
    "guilty": ["内疚", "有罪", "愧疚", "罪"],
    "happy": ["快乐", "幸福", "高兴", "愉快"],
    "hateful": ["可恨", "憎恨", "仇恨", "憎恶"],
    "heartbroken": ["心碎", "伤心", "悲痛"],
    "hope": ["希望", "期望", "盼望"],
    "hopeful": ["希望", "有希望", "乐观", "期待"],
    "horrified": ["恐惧", "惊恐", "骇然", "震惊"],
    "hostile": ["敌对", "敌意", "仇视"],
    "humiliated": ["羞辱", "屈辱", "耻辱", "丢脸"],
    "hurt": ["受伤", "伤害", "痛", "伤心"],
    "hysterical": ["歇斯底里", "疯狂", "失控"],
    "impatient": ["不耐烦", "急躁", "焦急"],
    "indifferent": ["冷漠", "漠不关心", "无所谓"],
    "indignant": ["愤慨", "气愤", "义愤"],
    "infatuated": ["迷恋", "痴迷", "着迷"],
    "inspired": ["灵感", "激励", "鼓舞", "启发"],
    "insulted": ["侮辱", "羞辱", "得罪", "冒犯"],
    "invigorated": ["精力充沛", "焕发", "活力", "振奋"],
    "irate": ["愤怒", "暴怒", "生气"],
    "irritated": ["恼火", "烦躁", "刺激", "恼怒"],
    "jealous": ["嫉妒", "妒忌", "吃醋"],
    "joyful": ["快乐", "喜悦", "欢乐", "欢快"],
    "jubilant": ["欢腾", "喜悦", "欢呼", "狂欢"],
    "kind": ["善良", "亲切", "好心", "爱心"],
    "lazy": ["懒惰", "懒散", "懒"],
    "listless": ["无精打采", "倦怠", "萎靡"],
    "lonely": ["孤独", "寂寞", "孤单"],
    "loving": ["爱", "慈爱", "深情", "爱心"],
    "mad": ["生气", "愤怒", "疯狂", "发疯"],
    "melancholy": ["忧郁", "惆怅", "伤感"],
    "miserable": ["悲惨", "痛苦", "凄惨", "难受"],
    "mortified": ["羞愧", "尴尬", "难堪"],
    "mystified": ["困惑", "迷惑", "不解"],
    "nervous": ["紧张", "不安", "焦虑"],
    "nostalgic": ["怀旧", "思念", "怀念"],
    "obstinate": ["固执", "顽固", "倔强"],
    "offended": ["冒犯", "得罪", "生气", "不快"],
    "on edge": ["紧张", "不安", "焦躁"],
    "optimistic": ["乐观", "积极", "看好"],
    "outraged": ["愤怒", "义愤", "震怒"],
    "overwhelmed": ["不堪重负", "淹没", "压倒", "崩溃"],
    "panicked": ["恐慌", "惊慌", "慌乱"],
    "paranoid": ["偏执", "多疑", "妄想"],
    "patient": ["耐心", "忍耐", "有耐心"],
    "peaceful": ["和平", "平静", "安宁", "宁静"],
    "perplexed": ["困惑", "迷惑", "不解"],
    "playful": ["顽皮", "淘气", "好玩", "活泼"],
    "pleased": ["高兴", "满意", "愉快", "欣喜"],
    "proud": ["自豪", "骄傲", "得意"],
    "puzzled": ["困惑", "疑惑", "不解", "迷惑"],
    "rattled": ["慌乱", "不安", "惊慌"],
    "reflective": ["反思", "沉思", "深思"],
    "refreshed": ["清爽", "焕然一新", "恢复"],
    "regretful": ["后悔", "遗憾", "懊悔"],
    "rejuvenated": ["焕发青春", "恢复活力", "焕然一新", "活力"],
    "relaxed": ["放松", "轻松", "舒适", "悠闲"],
    "relieved": ["宽慰", "解脱", "安心", "松了口气"],
    "remorseful": ["悔恨", "懊悔", "内疚"],
    "resentful": ["怨恨", "愤恨", "不满"],
    "resigned": ["认命", "无奈", "顺从", "听天由命"],
    "restless": ["不安", "焦躁", "坐立不安"],
    "sad": ["悲伤", "伤心", "难过", "忧伤"],
    "safe": ["安全", "平安", "保险"],
    "satisfied": ["满意", "满足", "称心"],
    "scared": ["害怕", "惊吓", "恐惧", "吓"],
    "scornful": ["轻蔑", "鄙视", "嘲讽", "讽刺"],
    "self-confident": ["自信", "有信心"],
    "self-conscious": ["不自在", "拘谨", "自我意识"],
    "self-critical": ["自责", "自我批评", "自我检讨"],
    "sensitive": ["敏感", "感性", "细腻"],
    "sentimental": ["感伤", "多愁善感", "感人"],
    "serene": ["宁静", "安详", "平静", "柔和"],
    "shaken": ["震惊", "动摇", "颤抖", "不安"],
    "shocked": ["震惊", "惊愕", "吃惊", "震撼"],
    "skeptical": ["怀疑", "质疑", "多疑"],
    "sleepy": ["困", "瞌睡", "昏昏欲睡", "睡意"],
    "sluggish": ["迟缓", "缓慢", "呆滞", "无力"],
    "smug": ["自鸣得意", "沾沾自喜", "得意"],
    "sorry": ["抱歉", "对不起", "遗憾", "难过"],
    "spiteful": ["恶意", "怨恨", "刻薄", "有毒"],
    "stimulated": ["刺激", "兴奋", "激发"],
    "stressed": ["压力", "紧张", "焦虑"],
    "stubborn": ["固执", "顽固", "倔强"],
    "stuck": ["卡住", "困住", "陷入", "无法"],
    "sullen": ["阴沉", "闷闷不乐", "愠怒"],
    "surprised": ["惊讶", "吃惊", "意外", "震惊"],
    "suspicious": ["怀疑", "可疑", "多疑", "嫌"],
    "sympathetic": ["同情", "体谅", "有同情心"],
    "tense": ["紧张", "绷紧", "焦虑"],
    "terrified": ["恐惧", "惊恐", "害怕", "吓坏"],
    "thankful": ["感谢", "感激", "感恩"],
    "thrilled": ["激动", "兴奋", "欣喜", "狂欢"],
    "tired": ["疲倦", "累", "疲劳", "疲惫"],
    "tormented": ["折磨", "痛苦", "煎熬"],
    "trapped": ["困住", "陷阱", "被困", "束缚"],
    "triumphant": ["胜利", "得意", "凯旋", "欢呼"],
    "troubled": ["困扰", "苦恼", "不安", "烦恼"],
    "uneasy": ["不安", "忐忑", "不自在"],
    "unhappy": ["不快乐", "不高兴", "难过", "伤心"],
    "unnerved": ["不安", "慌乱", "害怕"],
    "unsettled": ["不安", "动荡", "不稳定"],
    "upset": ["心烦", "难过", "不安", "沮丧"],
    "valiant": ["勇敢", "英勇", "勇猛"],
    "vengeful": ["报复", "复仇", "仇恨"],
    "vibrant": ["充满活力", "生机勃勃", "活力", "绚丽", "璀璨"],
    "vigilant": ["警惕", "警觉", "戒备"],
    "vindictive": ["报复", "怀恨", "恶意"],
    "vulnerable": ["脆弱", "无助", "易受伤害"],
    "weary": ["疲惫", "疲倦", "厌倦", "疲劳"],
    "worn out": ["疲惫", "精疲力尽", "磨损", "累"],
    "worried": ["担心", "忧虑", "焦虑", "担忧"],
    "worthless": ["无价值", "没用", "一文不值"],
}

#: emotion -> English near-synonyms and morphological variants, EXCLUDING the lemma
#: itself (the lemma and its inflections are what GATE A already tests). Matched
#: case-insensitively against the whitespace-stripped token.
EMOTION_EN_SYNONYMS: dict[str, list[str]] = {
    "afraid": ["fear", "fears", "feared", "fearful", "scared", "frightened", "terror", "dread"],
    "alarmed": ["alarm", "alarming", "startled", "panic"],
    "alert": ["alertness", "vigilant", "watchful", "warning"],
    "amazed": ["amazing", "amazement", "astonished", "wonder", "awe"],
    "amused": ["amusing", "amusement", "funny", "laugh", "humor"],
    "angry": ["anger", "angrily", "mad", "rage", "furious", "irate"],
    "annoyed": ["annoying", "annoyance", "irritated", "irritation", "bother"],
    "anxious": ["anxiety", "worried", "worry", "nervous", "uneasy"],
    "aroused": ["arousal", "excited", "stimulated", "stimulation"],
    "ashamed": ["shame", "shameful", "embarrassed", "humiliated"],
    "astonished": ["astonishing", "astonishment", "amazed", "shocked", "stunned"],
    "at ease": ["ease", "relaxed", "comfortable", "calm"],
    "awestruck": ["awe", "awed", "wonder", "marvel"],
    "bewildered": ["bewilderment", "confused", "confusion", "puzzled"],
    "bitter": ["bitterness", "resentful", "resentment", "sour"],
    "blissful": ["bliss", "happy", "joy", "ecstasy"],
    "bored": ["boredom", "boring", "dull", "tedious"],
    "brooding": ["brood", "moody", "gloomy", "pensive"],
    "calm": ["calmness", "calmly", "peaceful", "serene", "tranquil"],
    "cheerful": ["cheer", "cheery", "happy", "joyful", "merry"],
    "compassionate": ["compassion", "sympathy", "sympathetic", "kindness", "empathy"],
    "contemptuous": ["contempt", "scorn", "scornful", "disdain"],
    "content": ["contentment", "satisfied", "satisfaction", "pleased"],
    "defiant": ["defiance", "defy", "rebellious", "resist"],
    "delighted": ["delight", "delightful", "pleased", "joy", "happy"],
    "dependent": ["dependence", "dependency", "reliant", "rely"],
    "depressed": ["depression", "depressing", "sad", "despondent"],
    "desperate": ["desperation", "despair", "hopeless", "frantic"],
    "disdainful": ["disdain", "contempt", "contemptuous", "scorn"],
    "disgusted": ["disgust", "disgusting", "revulsion", "repulsed"],
    "disoriented": ["disorientation", "confused", "confusion", "lost", "dizzy"],
    "dispirited": ["discouraged", "downhearted", "demoralized", "dejected"],
    "distressed": ["distress", "distressing", "anguish", "upset", "suffering"],
    "disturbed": ["disturb", "disturbing", "disturbance", "troubled", "upset"],
    "docile": ["obedient", "submissive", "meek", "tame"],
    "droopy": ["droop", "drooping", "listless", "sluggish", "limp"],
    "dumbstruck": ["dumbfounded", "speechless", "stunned", "astonished"],
    "eager": ["eagerness", "eagerly", "keen", "enthusiastic"],
    "ecstatic": ["ecstasy", "elated", "euphoric", "thrilled"],
    "elated": ["elation", "ecstatic", "euphoric", "exhilarated", "joyful"],
    "embarrassed": ["embarrassment", "embarrassing", "awkward", "ashamed"],
    "empathetic": ["empathy", "empathic", "sympathetic", "compassion"],
    "energized": ["energy", "energetic", "invigorated", "vigor"],
    "enraged": ["rage", "enrage", "furious", "fury", "outraged"],
    "enthusiastic": ["enthusiasm", "eager", "keen", "passionate"],
    "envious": ["envy", "jealous", "jealousy", "covet"],
    "euphoric": ["euphoria", "ecstatic", "elated", "blissful"],
    "exasperated": ["exasperation", "frustrated", "irritated", "annoyed"],
    "excited": ["excitement", "exciting", "thrilled", "eager"],
    "exuberant": ["exuberance", "lively", "vivacious", "energetic"],
    "frightened": ["fright", "frighten", "frightening", "scared", "afraid", "terror"],
    "frustrated": ["frustration", "frustrating", "thwarted", "exasperated"],
    "fulfilled": ["fulfillment", "fulfilling", "satisfied", "content"],
    "furious": ["fury", "furiously", "enraged", "rage", "irate", "anger"],
    "gloomy": ["gloom", "dismal", "melancholy", "dreary"],
    "grateful": ["gratitude", "thankful", "thanks", "appreciation"],
    "greedy": ["greed", "greedily", "avarice", "covetous"],
    "grief-stricken": ["grief", "grieving", "mourning", "sorrow", "bereaved"],
    "grumpy": ["grouchy", "irritable", "cranky", "surly"],
    "guilty": ["guilt", "remorse", "remorseful", "blame"],
    "happy": ["happiness", "happily", "joy", "joyful", "glad"],
    "hateful": ["hate", "hatred", "loathing", "detest"],
    "heartbroken": ["heartbreak", "heartbreaking", "devastated", "grief"],
    "hope": ["hopeful", "hoping", "hopes", "wish", "optimism"],
    "hopeful": ["hope", "hopefulness", "optimistic", "promising"],
    "horrified": ["horror", "horrible", "horrifying", "terrified", "appalled"],
    "hostile": ["hostility", "antagonistic", "aggressive", "unfriendly"],
    "humiliated": ["humiliation", "humiliating", "shamed", "degraded"],
    "hurt": ["hurting", "pain", "painful", "wounded", "injured"],
    "hysterical": ["hysteria", "frantic", "frenzied", "uncontrollable"],
    "impatient": ["impatience", "restless", "eager", "hasty"],
    "indifferent": ["indifference", "apathetic", "uncaring", "detached"],
    "indignant": ["indignation", "outraged", "resentful", "affronted"],
    "infatuated": ["infatuation", "obsessed", "enamored", "smitten"],
    "inspired": ["inspiration", "inspiring", "motivated", "uplifted"],
    "insulted": ["insult", "insulting", "offended", "affront"],
    "invigorated": ["invigorating", "energized", "refreshed", "revitalized"],
    "irate": ["ire", "angry", "anger", "furious", "enraged"],
    "irritated": ["irritation", "irritating", "annoyed", "agitated"],
    "jealous": ["jealousy", "envious", "envy", "possessive"],
    "joyful": ["joy", "joyous", "happy", "delighted", "glad"],
    "jubilant": ["jubilation", "celebrating", "triumphant", "elated"],
    "kind": ["kindness", "kindly", "caring", "gentle", "nice"],
    "lazy": ["laziness", "idle", "sluggish", "indolent"],
    "listless": ["lethargic", "apathetic", "sluggish", "languid"],
    "lonely": ["loneliness", "alone", "isolated", "solitary"],
    "loving": ["love", "loved", "affectionate", "tender", "caring"],
    "mad": ["madness", "angry", "anger", "furious", "crazy"],
    "melancholy": ["melancholic", "sadness", "gloom", "wistful"],
    "miserable": ["misery", "wretched", "unhappy", "suffering"],
    "mortified": ["mortification", "humiliated", "embarrassed", "ashamed"],
    "mystified": ["mystery", "mystifying", "puzzled", "baffled", "confused"],
    "nervous": ["nervousness", "anxious", "anxiety", "jittery", "tense"],
    "nostalgic": ["nostalgia", "wistful", "reminiscent", "longing"],
    "obstinate": ["obstinacy", "stubborn", "headstrong", "unyielding"],
    "offended": ["offense", "offence", "offensive", "insulted", "affronted"],
    "on edge": ["edgy", "tense", "jumpy", "nervous", "anxious"],
    "optimistic": ["optimism", "hopeful", "positive", "upbeat"],
    "outraged": ["outrage", "outrageous", "furious", "indignant"],
    "overwhelmed": ["overwhelming", "swamped", "overcome", "overloaded"],
    "panicked": ["panic", "panicking", "frantic", "terror"],
    "paranoid": ["paranoia", "suspicious", "distrustful"],
    "patient": ["patience", "tolerant", "forbearing"],
    "peaceful": ["peace", "tranquil", "serene", "calm"],
    "perplexed": ["perplexity", "puzzled", "confused", "baffled"],
    "playful": ["play", "playfulness", "mischievous", "frisky"],
    "pleased": ["pleasure", "pleasing", "glad", "satisfied", "delighted"],
    "proud": ["pride", "proudly", "dignity"],
    "puzzled": ["puzzle", "puzzling", "confused", "baffled", "perplexed"],
    "rattled": ["rattle", "shaken", "unnerved", "flustered"],
    "reflective": ["reflection", "contemplative", "pensive", "thoughtful"],
    "refreshed": ["refresh", "refreshing", "rejuvenated", "revitalized"],
    "regretful": ["regret", "remorseful", "sorry", "rueful"],
    "rejuvenated": ["rejuvenation", "refreshed", "revitalized", "renewed"],
    "relaxed": ["relax", "relaxation", "calm", "comfortable"],
    "relieved": ["relief", "relieving", "reassured", "eased"],
    "remorseful": ["remorse", "regretful", "contrite", "guilty"],
    "resentful": ["resentment", "bitter", "grudge", "indignant"],
    "resigned": ["resignation", "accepting", "submissive", "defeated"],
    "restless": ["restlessness", "agitated", "fidgety", "uneasy"],
    "sad": ["sadness", "sorrow", "sorrowful", "unhappy", "grief", "sorry"],
    "safe": ["safety", "secure", "security", "protected"],
    "satisfied": ["satisfaction", "satisfying", "content", "pleased"],
    "scared": ["scare", "scary", "afraid", "frightened", "fear"],
    "scornful": ["scorn", "contempt", "contemptuous", "derisive"],
    "self-confident": ["confidence", "confident", "assured"],
    "self-conscious": ["awkward", "embarrassed", "shy", "insecure"],
    "self-critical": ["self-criticism", "self-blame", "self-reproach"],
    "sensitive": ["sensitivity", "delicate", "touchy", "receptive"],
    "sentimental": ["sentiment", "sentimentality", "nostalgic", "emotional"],
    "serene": ["serenity", "tranquil", "peaceful", "calm"],
    "shaken": ["shake", "shaking", "rattled", "unnerved", "shocked"],
    "shocked": ["shock", "shocking", "stunned", "astonished", "appalled"],
    "skeptical": ["skepticism", "doubtful", "doubt", "dubious", "suspicious"],
    "sleepy": ["sleep", "sleepiness", "drowsy", "tired", "dozy"],
    "sluggish": ["slow", "lethargic", "listless", "torpid"],
    "smug": ["smugness", "complacent", "self-satisfied"],
    "sorry": ["apology", "apologetic", "regret", "regretful"],
    "spiteful": ["spite", "malicious", "vindictive", "malice"],
    "stimulated": ["stimulation", "stimulating", "excited", "aroused"],
    "stressed": ["stress", "stressful", "tense", "pressure", "strain"],
    "stubborn": ["stubbornness", "obstinate", "headstrong", "willful"],
    "stuck": ["trapped", "blocked", "immobilized", "jammed"],
    "sullen": ["sulky", "morose", "glum", "moody"],
    "surprised": ["surprise", "surprising", "astonished", "startled", "amazed"],
    "suspicious": ["suspicion", "suspect", "distrustful", "skeptical"],
    "sympathetic": ["sympathy", "compassionate", "empathetic", "understanding"],
    "tense": ["tension", "taut", "stressed", "edgy", "anxious"],
    "terrified": ["terror", "terrify", "terrifying", "horrified", "frightened"],
    "thankful": ["thanks", "thankfulness", "grateful", "gratitude"],
    "thrilled": ["thrill", "thrilling", "excited", "elated", "exhilarated"],
    "tired": ["tiredness", "fatigue", "exhausted", "weary", "sleepy"],
    "tormented": ["torment", "torture", "anguish", "agony"],
    "trapped": ["trap", "trapping", "stuck", "confined", "caged"],
    "triumphant": ["triumph", "victorious", "victory", "exultant"],
    "troubled": ["trouble", "troubling", "distressed", "worried"],
    "uneasy": ["unease", "uneasiness", "anxious", "apprehensive", "restless"],
    "unhappy": ["unhappiness", "sad", "sadness", "miserable", "displeased"],
    "unnerved": ["unnerving", "rattled", "shaken", "disconcerted"],
    "unsettled": ["unsettling", "uneasy", "disturbed", "restless"],
    "upset": ["upsetting", "distressed", "disturbed", "troubled"],
    "valiant": ["valor", "brave", "bravery", "courageous", "heroic"],
    "vengeful": ["vengeance", "revenge", "vindictive", "retaliatory"],
    "vibrant": ["vibrancy", "lively", "energetic", "vivid"],
    "vigilant": ["vigilance", "watchful", "alert", "wary"],
    "vindictive": ["vindictiveness", "vengeful", "revenge", "spiteful"],
    "vulnerable": ["vulnerability", "fragile", "defenseless", "exposed"],
    "weary": ["weariness", "tired", "fatigue", "exhausted", "worn"],
    "worn out": ["worn", "exhausted", "tired", "spent", "depleted"],
    "worried": ["worry", "worrying", "anxious", "concerned", "apprehensive"],
    "worthless": ["worthlessness", "useless", "valueless", "insignificant"],
}


def gloss(token: str) -> str:
    """English gloss for a CJK token, or '' when it is not in the glossary."""
    return TOKEN_GLOSS.get(str(token).strip(), "")


def matches_chinese(token: str, emotion: str) -> bool:
    """Exact-equality match of ``token`` against ``emotion``'s Chinese renderings."""
    return str(token).strip() in EMOTION_ZH.get(emotion, [])


def matches_en_synonym(token: str, emotion: str) -> bool:
    """Exact-equality match against ``emotion``'s English near-synonyms."""
    return str(token).strip().lower() in {
        s.lower() for s in EMOTION_EN_SYNONYMS.get(emotion, [])
    }
